version: '3.8'

volumes:
  collected_static: {}
  media: {}
  logs: {}

services:
   web:
       restart: always
       build:
           context: .
           dockerfile: ./compose/django/Dockerfile
       container_name: web_test_django
       command: python manage.py runserver 0.0.0.0:8010
       ports:
           - 8010:8010
       volumes:
#         - collected_static:/src/collected_static:ro
#         - media:/src/media:ro
#         - logs:/src/logs:ro
         - .:/src